### ISSUE TITLE
How do I update the snapshots automatically?

### ISSUE THREAD

**Issue by edvn0** [origin-energy/java-snapshot-testing#104]
I don't understand how to supply the -PupdateSnapshot flag. Maven does not recognize the profile, and I don't think that's a valid VM option. How do we update all snapshots?

**Comment by jackmatt2** [comment]
It's passed as a system property `System.getProperty`

I think for maven the following should work
```
mvn test -DupdateSnapshot
```

**Comment by edvn0** [comment]
Seems it does not work. Neither does
```sh
MAVEN_OPTS=-DupdateSnapshot mvn test
```

What am I doing wrong here?

**Comment by jackmatt2** [comment]
Can you do this

First - try passing a value to updateSnapshot
```
mvn test -DupdateSnapshot=true
```

If that still fails, try this

Inside your `@Test`
```
System.out.println("UPDATE SNAPSHOT: " + System.getProperty("updateSnapshot"))
```

Then
```
mvn test -DupdateSnapshot=foobar
```

If you don't see "UPDATE SNAPSHOT: foobar" printed to the console - I suspect maven isn't making the system property available to the actual test.

On the other hand, If it does print - it might be a bug in this library.

**Comment by edvn0** [comment]
I added a profile which used the property like so:
```sh
mvn test -DupdateSnapshot
```
to the Surefire configuration via the <argLine></argLine> property.

Presumably, Maven could not find the VM args from my terminal for some reason. This works fine.

**Comment by blutorange** [comment]
For reference, the reason why it does not work when you set a system property normally is that the Maven surefire / failsafe plugin [creates a forked JVM](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkcount) where it runs the tests (to ensure only the required dependencies are on the classpath). So any properties set on the original JVM running the Maven process won't be present in the tests.

For this reason, the plugin provides a configuration option to set system variables. Properties for tests need to be set like this via the plugin:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <updateSnapshot>all</updateSnapshot>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```

(You can of course use a property like `<updateSnapshot>${update-snapshot}</updateSnapshot>` instead of hard-coding the value).
