### ISSUE TITLE
DeterministicJacksonSnapshotSerializer does not work with unordered list of objects

### ISSUE THREAD

**Issue by zlzzk0** [origin-energy/java-snapshot-testing#170]
I have an unordered list of objects that changes order every time the test runs. This causes test to fail because order is different when matching the snapshot. I tried DeterministicJacksonSnapshotSerializer but this seems work only for a list of strings but not for list of objects

Here is a single example to replicate
```
@ExtendWith(SnapshotExtension::class)
class ATest {
    private lateinit var expect: Expect

    @Test
    fun test() {
       val aa = listOf(
            mapOf("a" to "a"), mapOf("b" to "b"), mapOf("c" to "c"),
        ).shuffled()

        expect.serializer("orderedJson").toMatchSnapshot(aa)
    }
}
```

snapshot.properties
```
serializer=au.com.origin.snapshots.serializers.v1.ToStringSnapshotSerializer
serializer.base64=au.com.origin.snapshots.serializers.v1.Base64SnapshotSerializer
serializer.json=au.com.origin.snapshots.jackson.serializers.v1.JacksonSnapshotSerializer
serializer.orderedJson=au.com.origin.snapshots.jackson.serializers.v1.DeterministicJacksonSnapshotSerializer
comparator=au.com.origin.snapshots.comparators.v1.PlainTextEqualsComparator
reporters=au.com.origin.snapshots.reporters.v1.PlainTextSnapshotReporter
output-dir=src/test/kotlin
snapshot-dir=__snapshots__
ci-env-var=CI

```

version is 4.0.8. I also tried other serializers but none works

**Comment by jackmatt2** [comment]
Thanks, I can replicate this issue locally.

**Comment by jackmatt2** [comment]
I did some experimentation and have concluded that this is not a bug.  

In this case you have a  list of Maps and you are shuffling that map in order to change the order the map instances are displayed.  

I think you are expecting the library to re-order it so that maps with a key of "a" are at the top and "c" at the bottom.  This is kind of an unreasonable ask.

For example consider the following.  What is the correct output order?  
```
       val aa = listOf(
            mapOf("a" to "a", "b" to "b"), mapOf("b" to "b", "a" to "a"),
        ).shuffled()
```

`DeterministicJacksonSnapshotSerializer` will order the Lists & Map keys. It is up do you to ensure Determinism after that.
