### ISSUE TITLE
Add an option to include a \n at the end of the .snap

### ISSUE THREAD

**Issue by Brunomachadob** [origin-energy/java-snapshot-testing#35]
Hey!

Maybe we could include a `boolean includeNewLineAtEnd` into the `SnapshotConfig`, so anyone who desires can enable it.

As of the default option

1. `true` by default, so this would be a breaking change that people would need to override if they don't want to change all files at once (I'm not expecting this shouldn't break the test, but only mark the file as changed to git);
2. `false` by default, so this won't break any snapshot already created and people will need to implement the config and override.

What do you think?
Any suggestions?

I'm open to work on this feature.

**Comment by jackmatt2** [comment]
What's the use case?

**Comment by jackmatt2** [comment]
I generally have found adding configuration like his is a trap because you end up with a huge number of small config which end up bloating out the API.  Sometimes the config conflicts in some way with other config.  

I think you will be able to achieve what you want with the new `expect(...).serializer(MyCustomSerializer.class)` API anyway.

```
public class MyCustomSerializer extends JacksonSnapshotSerializer {

    @Override
    public void configure(ObjectMapper objectMapper) {
        // configure object mapper to put line at the end
    }
}
```

**Comment by jackmatt2** [comment]
Above wont work actually because it's at snapshot level.  Is this due to a code formatter or something adding the space to the end of the file?

**Comment by Brunomachadob** [comment]
Hey, yes this is about code formatter/linting, that by default all files end with an empty line.
Yes, the custom serializer or some sort of transformer hook would solve the problem.

**Comment by jackmatt2** [comment]
@Brunomachadob are you still available to work on this?

I'm thinking something like this in `SnapshotConfig`
```
default String onSaveSnapshotFile(String snapshots) {
  return snapshots;
}
```

But you might come up with a better idea.

From some initial investigation -  I believe this needs to go into the verifier because it needs to happen once all `@Test` methods have finished.

**Comment by Brunomachadob** [comment]
Hey, yep. I can try to check this.

**Comment by jackmatt2** [comment]
This is still on the SNAPSHOT release but you can now do what you want by overriding this:https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/SnapshotConfig.java#L107-L109
