### ISSUE TITLE
Triple newlines can be generated by the toString serializer and cause false negatives

### ISSUE THREAD

**Issue by douira** [origin-energy/java-snapshot-testing#90]
The ToStringSnapshotSerializer can generate a string that contains triple newlines, the reserved sequence, if adjacent objects contain one newline at the border each. [This code](https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/serializers/ToStringSnapshotSerializer.java#L28) in the serializer can produce triple non-escaped newlines if one object has the string "...\n" and one has the string "\n...". The resulting string contains triple newlines and breaks snapshot tests where running the same test will error on the second run because of the unescaped sequence.
Additionally I've found that if the scenario content ends with two newlines then the newline added before the scenario end marker `]` can also combine to form a spurious triple newline that breaks tests. (the same thing happens at the beginning)
Since my tests involve a lot of newlines, would it maybe be possible to expose an API to simply change the scenario separator from three newlines to something else?

**Comment by jackmatt2** [comment]
I'm thinking this only happens when using varargs param right.  

Yeah this is a problem.
```
expect.toMatchSnapshot("A ","  B")
```
I was thinking of removing the varargs param in a future version of this library because of another issue I was having with it.  This scenario confirms my thought that maybe it's a bad idea.

Let me thing about a solution, in the meantime you might need to RightTrim your objects or don't use the varargs param and join your string yourself
```
expect.toMatchSnapshot("A " + "  B")
```

**Comment by douira** [comment]
Yeah it only happens when multiple strings are passed. My workaround has been to join them into a string manually with newlines. Then the built-in triple newline detection can come into action when necessary.
